version: "3"

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: Facebook_scrapper_api
    volumes:
      - ~mongodb-data:/data/db
    ports:
      - 27017:27017
    networks : 
      - mongodb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    volumes:
      - ~mongodb-data:/data/db
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks : 
      - mongodb_network
volumes:
  mongodb-data :
    name: mongodb-data
networks:
  mongodb_network : 
    name : mongodb_network
